SETTING:brightness:180
SETTING:gaugeId:0
SETTING:gaugeCanId:0x500
SETTING:selectedSetting:0
SETTING:gaugeCount:4
SETTING:wifiEnabled:0
SETTING:espNowEnabled:0
SETTING:espNowHostMode:0
SETTING:espNowMacFilter:0
SETTING:espNowHostMac:
SETTING:telnetEnabled:0
SETTING:revLimitSourceIndex:0
SETTING:shiftLight:6800
SETTING:shiftLightStep:250
SETTING:demoBoostLimitX10:150
SETTING:bootDelayMs:0
SETTING:showBootImage:1
SETTING:canBusLink:1
SETTING:canRxPin:42
SETTING:canTxPin:43
SETTING:canRsPin:44
SETTING:buttonPressedCanEventId:2
SETTING:simpleGaugeIndicator:0
SETTING:simpleGaugeColor:0
SETTING:displayErrors:0
SETTING:displayStatus:0
SETTING:limitGaugeValues:1
SETTING:showNeedle:1
SETTING:buttonMode:0
SETTING:chartUpdateRateMs:70
SELECTED:0: 1,2,3
SELECTED:1: 1,2,3
SELECTED:2: 1,2,3
SELECTED:3: 1,2,3
SELECTED:4: 1,2,3
SELECTED:5: 1,2,3
FAVORITES:0: 1,2,3
FAVORITES:1: 1,2,3
FAVORITES:2: 1,2,3
FAVORITES:3: 1,2,3
FAVORITES:4: 1,2,3
FAVORITES:5: 1,2,3
STARTSCREEN:0
